=== aig-hagen/aig-causal-knowledge-base-editor/src/assets/graphical-causal-knowledge-base-v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://causal-knowledge-base-editor.aig.fernuni-hagen.de/graphical-causal-knowledge-base-v1.schema.json",
  "$defs": {
    "id": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "position": {
      "type": "object",
      "additionalProperties": false,
      "required": ["x", "y"],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      }
    },
    "atom": {
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "name", "description", "position"],
      "properties": {
        "id": {
          "$ref": "#/$defs/id"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "assumption": {
          "enum": [1, 2, 3, 4, 5]
        },
        "position": {
          "$ref": "#/$defs/position"
        }
      }
    },
    "conjunction": {
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "type", "position"],
      "properties": {
        "id": {
          "$ref": "#/$defs/id"
        },
        "type": { "const": "conjunction" },
        "position": {
          "$ref": "#/$defs/position"
        }
      }
    },
    "connectionId": {
      "type": "object",
      "additionalProperties": false,
      "required": ["sourceId", "targetId"],
      "properties": {
        "sourceId": {
          "$ref": "#/$defs/id"
        },
        "targetId": {
          "$ref": "#/$defs/id"
        }
      }
    },
    "connection": {
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "negated"],
      "properties": {
        "id": {
          "$ref": "#/$defs/connectionId"
        },
        "negated": {
          "type": "boolean"
        }
      }
    }
  },
  "title": "Graphical causal knowledge base",
  "description": "Graphcial represenation of causal knowledge base.",
  "type": "object",
  "additionalProperties": false,
  "required": ["apiVersion", "atoms", "operators", "connections"],
  "properties": {
    "apiVersion": {
      "const": "graphical/v1"
    },
    "atoms": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/atom"
      }
    },
    "operators": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/conjunction"
      }
    },
    "connections": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/connection"
      }
    }
  }
}

=== aig-hagen/aig-causal-knowledge-base-editor/src/assets/examples/diagnosis.json
{
  "apiVersion": "graphical/v1",
  "atoms": [
    {
      "id": 0,
      "name": "at-risk",
      "description": "",
      "assumption": 3,
      "position": {
        "x": 320,
        "y": 387
      }
    },
    {
      "id": 2,
      "name": "corona",
      "description": "",
      "assumption": 3,
      "position": {
        "x": 521,
        "y": 392
      }
    },
    {
      "id": 4,
      "name": "influenza",
      "description": "",
      "assumption": 3,
      "position": {
        "x": 782,
        "y": 385
      }
    },
    {
      "id": 6,
      "name": "covid",
      "description": "",
      "position": {
        "x": 552,
        "y": 639
      }
    },
    {
      "id": 8,
      "name": "flue",
      "description": "",
      "position": {
        "x": 742,
        "y": 643
      }
    },
    {
      "id": 10,
      "name": "fever",
      "description": "",
      "position": {
        "x": 663,
        "y": 881
      }
    },
    {
      "id": 12,
      "name": "chills",
      "description": "",
      "position": {
        "x": 618,
        "y": 1076
      }
    },
    {
      "id": 14,
      "name": "short-of-breath",
      "description": "",
      "position": {
        "x": 318,
        "y": 1023
      }
    }
  ],
  "operators": [
    {
      "id": 1,
      "type": "conjunction",
      "position": {
        "x": 320,
        "y": 359
      }
    },
    {
      "id": 3,
      "type": "conjunction",
      "position": {
        "x": 521,
        "y": 364
      }
    },
    {
      "id": 5,
      "type": "conjunction",
      "position": {
        "x": 782,
        "y": 357
      }
    },
    {
      "id": 7,
      "type": "conjunction",
      "position": {
        "x": 520,
        "y": 611
      }
    },
    {
      "id": 9,
      "type": "conjunction",
      "position": {
        "x": 710,
        "y": 615
      }
    },
    {
      "id": 11,
      "type": "conjunction",
      "position": {
        "x": 599,
        "y": 853
      }
    },
    {
      "id": 13,
      "type": "conjunction",
      "position": {
        "x": 586,
        "y": 1048
      }
    },
    {
      "id": 15,
      "type": "conjunction",
      "position": {
        "x": 286,
        "y": 995
      }
    },
    {
      "id": 16,
      "type": "conjunction",
      "position": {
        "x": 650,
        "y": 1048
      }
    },
    {
      "id": 17,
      "type": "conjunction",
      "position": {
        "x": 663,
        "y": 853
      }
    },
    {
      "id": 18,
      "type": "conjunction",
      "position": {
        "x": 727,
        "y": 853
      }
    },
    {
      "id": 19,
      "type": "conjunction",
      "position": {
        "x": 774,
        "y": 615
      }
    },
    {
      "id": 20,
      "type": "conjunction",
      "position": {
        "x": 584,
        "y": 611
      }
    },
    {
      "id": 21,
      "type": "conjunction",
      "position": {
        "x": 350,
        "y": 995
      }
    }
  ],
  "connections": [
    {
      "id": {
        "sourceId": 1,
        "targetId": 0
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 3,
        "targetId": 2
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 5,
        "targetId": 4
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 7,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 9,
        "targetId": 8
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 11,
        "targetId": 10
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 13,
        "targetId": 12
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 15,
        "targetId": 14
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 10,
        "targetId": 13
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 16,
        "targetId": 12
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 6,
        "targetId": 11
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 17,
        "targetId": 10
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 8,
        "targetId": 17
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 18,
        "targetId": 10
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 4,
        "targetId": 9
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 19,
        "targetId": 8
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 2,
        "targetId": 7
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 20,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 6,
        "targetId": 15
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 21,
        "targetId": 14
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 0,
        "targetId": 15
      },
      "negated": false
    }
  ]
}

=== aig-hagen/aig-causal-knowledge-base-editor/src/modules/causal-knowledge/examples/drowning.json
{
  "apiVersion": "graphical/v1",
  "atoms": [
    {
      "id": 0,
      "name": "giant-wave",
      "description": "The victim has encountered a giant wave.",
      "assumption": 3,
      "position": {
        "x": 400,
        "y": 100
      }
    },
    {
      "id": 1,
      "name": "strong-current",
      "description": "The victim has encountered a strong current.",
      "assumption": 3,
      "position": {
        "x": 600,
        "y": 100
      }
    },
    {
      "id": 2,
      "name": "jellyfish",
      "description": "The victim has been stung by a jellyfish.",
      "assumption": 3,
      "position": {
        "x": 800,
        "y": 100
      }
    },
    {
      "id": 3,
      "name": "broken-board",
      "description": "The victim's surfboard has been broken.",
      "position": {
        "x": 300,
        "y": 300
      }
    },
    {
      "id": 4,
      "name": "submersion",
      "description": "The victim has been submerged in water.",
      "position": {
        "x": 500,
        "y": 300
      }
    },
    {
      "id": 5,
      "name": "cramp",
      "description": "The victim has had a cramp.",
      "position": {
        "x": 732,
        "y": 300
      }
    },
    {
      "id": 6,
      "name": "drowning",
      "description": "The victim has drowned.",
      "position": {
        "x": 632,
        "y": 500
      }
    }
  ],
  "operators": [
    {
      "id": 7,
      "type": "conjunction",
      "position": {
        "x": 400,
        "y": 72
      }
    },
    {
      "id": 8,
      "type": "conjunction",
      "position": {
        "x": 600,
        "y": 72
      }
    },
    {
      "id": 9,
      "type": "conjunction",
      "position": {
        "x": 800,
        "y": 72
      }
    },
    {
      "id": 10,
      "type": "conjunction",
      "position": {
        "x": 268,
        "y": 272
      }
    },
    {
      "id": 11,
      "type": "conjunction",
      "position": {
        "x": 468,
        "y": 272
      }
    },
    {
      "id": 12,
      "type": "conjunction",
      "position": {
        "x": 668,
        "y": 272
      }
    },
    {
      "id": 13,
      "type": "conjunction",
      "position": {
        "x": 568,
        "y": 472
      }
    },
    {
      "id": 14,
      "type": "conjunction",
      "position": {
        "x": 632,
        "y": 472
      }
    },
    {
      "id": 15,
      "type": "conjunction",
      "position": {
        "x": 696,
        "y": 472
      }
    },
    {
      "id": 16,
      "type": "conjunction",
      "position": {
        "x": 332,
        "y": 272
      }
    },
    {
      "id": 17,
      "type": "conjunction",
      "position": {
        "x": 532,
        "y": 272
      }
    },
    {
      "id": 18,
      "type": "conjunction",
      "position": {
        "x": 732,
        "y": 272
      }
    },
    {
      "id": 19,
      "type": "conjunction",
      "position": {
        "x": 796,
        "y": 272
      }
    }
  ],
  "connections": [
    {
      "id": {
        "sourceId": 7,
        "targetId": 0
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 8,
        "targetId": 1
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 9,
        "targetId": 2
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 10,
        "targetId": 3
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 11,
        "targetId": 4
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 12,
        "targetId": 5
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 13,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 4,
        "targetId": 13
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 14,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 5,
        "targetId": 14
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 15,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 0,
        "targetId": 10
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 16,
        "targetId": 3
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 0,
        "targetId": 11
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 17,
        "targetId": 4
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 1,
        "targetId": 11
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 1,
        "targetId": 12
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 18,
        "targetId": 5
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 2,
        "targetId": 18
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 19,
        "targetId": 5
      },
      "negated": false
    }
  ]
}

=== aig-hagen/aig-causal-knowledge-base-editor/src/modules/causal-knowledge/examples/diagnosis.json
{
  "apiVersion": "graphical/v1",
  "atoms": [
    {
      "id": 0,
      "name": "at-risk",
      "description": "The patient has been at risk for respiratory illness.",
      "assumption": 3,
      "position": {
        "x": 300,
        "y": 100
      }
    },
    {
      "id": 1,
      "name": "corona",
      "description": "The patient has been infected by the coronavirus.",
      "assumption": 3,
      "position": {
        "x": 500,
        "y": 100
      }
    },
    {
      "id": 2,
      "name": "influenza",
      "description": "The patient has been infected by the influenza virus.",
      "assumption": 3,
      "position": {
        "x": 700,
        "y": 100
      }
    },
    {
      "id": 3,
      "name": "covid",
      "description": "The patient has developed COVID.",
      "position": {
        "x": 500,
        "y": 300
      }
    },
    {
      "id": 4,
      "name": "flu",
      "description": "The patient has developed the flu.",
      "position": {
        "x": 700,
        "y": 300
      }
    },
    {
      "id": 5,
      "name": "fever",
      "description": "The patient has had a fever.",
      "position": {
        "x": 632,
        "y": 500
      }
    },
    {
      "id": 6,
      "name": "chills",
      "description": "The patient has experienced chills.",
      "position": {
        "x": 600,
        "y": 700
      }
    },
    {
      "id": 7,
      "name": "short-of-breath",
      "description": "The patient has been short of breath.",
      "position": {
        "x": 300,
        "y": 500
      }
    }
  ],
  "operators": [
    {
      "id": 8,
      "type": "conjunction",
      "position": {
        "x": 300,
        "y": 72
      }
    },
    {
      "id": 9,
      "type": "conjunction",
      "position": {
        "x": 500,
        "y": 72
      }
    },
    {
      "id": 10,
      "type": "conjunction",
      "position": {
        "x": 700,
        "y": 72
      }
    },
    {
      "id": 11,
      "type": "conjunction",
      "position": {
        "x": 468,
        "y": 272
      }
    },
    {
      "id": 12,
      "type": "conjunction",
      "position": {
        "x": 668,
        "y": 272
      }
    },
    {
      "id": 13,
      "type": "conjunction",
      "position": {
        "x": 568,
        "y": 472
      }
    },
    {
      "id": 14,
      "type": "conjunction",
      "position": {
        "x": 568,
        "y": 672
      }
    },
    {
      "id": 15,
      "type": "conjunction",
      "position": {
        "x": 268,
        "y": 472
      }
    },
    {
      "id": 16,
      "type": "conjunction",
      "position": {
        "x": 632,
        "y": 672
      }
    },
    {
      "id": 17,
      "type": "conjunction",
      "position": {
        "x": 632,
        "y": 472
      }
    },
    {
      "id": 18,
      "type": "conjunction",
      "position": {
        "x": 696,
        "y": 472
      }
    },
    {
      "id": 19,
      "type": "conjunction",
      "position": {
        "x": 732,
        "y": 272
      }
    },
    {
      "id": 20,
      "type": "conjunction",
      "position": {
        "x": 532,
        "y": 272
      }
    },
    {
      "id": 21,
      "type": "conjunction",
      "position": {
        "x": 332,
        "y": 472
      }
    }
  ],
  "connections": [
    {
      "id": {
        "sourceId": 8,
        "targetId": 0
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 9,
        "targetId": 1
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 10,
        "targetId": 2
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 11,
        "targetId": 3
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 12,
        "targetId": 4
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 13,
        "targetId": 5
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 14,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 15,
        "targetId": 7
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 5,
        "targetId": 14
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 16,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 3,
        "targetId": 13
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 17,
        "targetId": 5
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 4,
        "targetId": 17
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 18,
        "targetId": 5
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 2,
        "targetId": 12
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 19,
        "targetId": 4
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 1,
        "targetId": 11
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 20,
        "targetId": 3
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 3,
        "targetId": 15
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 21,
        "targetId": 7
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 0,
        "targetId": 15
      },
      "negated": false
    }
  ]
}

=== aig-hagen/aig-causal-knowledge-base-editor/src/assets/examples/drowning.json
{
  "apiVersion": "graphical/v1",
  "atoms": [
    {
      "id": 0,
      "name": "giant-wave",
      "description": "",
      "assumption": 3,
      "position": {
        "x": 299,
        "y": 330
      }
    },
    {
      "id": 1,
      "name": "strong-current",
      "description": "",
      "assumption": 3,
      "position": {
        "x": 511.5150562543759,
        "y": 331.621235936406
      }
    },
    {
      "id": 2,
      "name": "jellyfish",
      "description": "",
      "assumption": 3,
      "position": {
        "x": 731.28711403472,
        "y": 336.1782214913202
      }
    },
    {
      "id": 3,
      "name": "broken-board",
      "description": "",
      "position": {
        "x": 298,
        "y": 479
      }
    },
    {
      "id": 4,
      "name": "submersion",
      "description": "",
      "position": {
        "x": 515,
        "y": 481
      }
    },
    {
      "id": 5,
      "name": "cramp",
      "description": "",
      "position": {
        "x": 701,
        "y": 479
      }
    },
    {
      "id": 6,
      "name": "drowning",
      "description": "",
      "position": {
        "x": 590,
        "y": 597
      }
    }
  ],
  "operators": [
    {
      "id": 7,
      "type": "conjunction",
      "position": {
        "x": 449,
        "y": 411
      }
    }
  ],
  "connections": [
    {
      "id": {
        "sourceId": 4,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 5,
        "targetId": 6
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 2,
        "targetId": 5
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 1,
        "targetId": 7
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 0,
        "targetId": 7
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 7,
        "targetId": 4
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 0,
        "targetId": 3
      },
      "negated": false
    },
    {
      "id": {
        "sourceId": 1,
        "targetId": 5
      },
      "negated": false
    }
  ]
}
